#include<stdio.h>

int main(){
    char s[5] = "Hello";
    char t[5];

    int i;
    for(int i = 0; s[i] != '\0'; i++){
        t[i] = s[i];
    }
    printf("%s", t);
    return 0;
}

/*
The output is generated by the machine is "Helloello"
but we expect that will print "Hello", because of undefined behaviour
we hadn't initialized a room for the delimitor or '\0'. for that reason the loop is behaving undefined.
*/